version: "3"

services:
  mysql-db:
    image: mysql-custom:5.7
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
      - ./log:/var/log/mysql
    environment:
      TZ: "Asia/Bangkok"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
    ports:
      - "3306:3306"
